version: '3'

networks:
  counter:
    external: true

services:
  counter-db:
    container_name: counterdb
    image: postgres:10.7
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: counter
      POSTGRES_USER: counter
      POSTGRES_PASSWORD: counter-pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - counter