name: Java CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build app
        run: ./gradlew clean build
      - name: Login to docker.io
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - name: Build image
        run: docker build -t $LOGIN/$NAME:${{ github.sha }} -f Dockerfile .
      - name: Push image
        run: docker push $LOGIN/$NAME:${{ github.sha }}
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop ${echo ${{ secrets.DOCKER_NAME }}
            docker rm ${echo ${{ secrets.DOCKER_NAME }}
            docker run --name=${{ secrets.DOCKER_NAME }} --add-host=host.docker.internal:host-gateway -e "SPRING_PROFILES_ACTIVE=docker" -p 8080:8080 -d $LOGIN/$NAME:${{ github.sha }}